BEGIN;

ALTER TABLE site_settings
  ADD COLUMN IF NOT EXISTS contact_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_location TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_hours TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS smtp_host TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_port INTEGER NOT NULL DEFAULT 587,
  ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS smtp_user TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_pass TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_from TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS smtp_to TEXT NOT NULL DEFAULT '';

COMMIT;
